export enum ConfigKey {
  NODE_ENV = 'NODE_ENV',
  FRONTEND_HOST = 'FRONTEND_HOST',
  PORT = 'PORT',
  ENABLE_SWAGGER = 'ENABLE_SWAGGER',

  POSTGRES_TIMEZONE = 'POSTGRES_TIMEZONE',
  POSTGRES_DB_NAME = 'POSTGRES_DB_NAME',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_DEBUG_MODE = 'POSTGRES_DEBUG_MODE',

  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',

  MAIL_HOST = 'MAIL_HOST',
  MAIL_PORT = 'MAIL_PORT',
  MAIL_USER = 'MAIL_USER',
  MAIL_PASS = 'MAIL_PASS',
  MAILDEV_WEB_PORT = 'MAILDEV_WEB_PORT',

  ENCRYPTION_KEY = 'ENCRYPTION_KEY',
  WEBDAV_BASE_URL = 'WEBDAV_BASE_URL',
  WEBDAV_USERNAME = 'WEBDAV_USERNAME',
  WEBDAV_PASSWORD = 'WEBDAV_PASSWORD',
  WEBDAV_TIMEOUT = 'WEBDAV_TIMEOUT',

  // Media Processing
  FFMPEG_PATH = 'FFMPEG_PATH',
  TEMP_DIR = 'TEMP_DIR',
  MAX_CONCURRENT_JOBS = 'MAX_CONCURRENT_JOBS',

  // File Storage
  UPLOAD_DIR = 'UPLOAD_DIR',
  MAX_FILE_SIZE = 'MAX_FILE_SIZE',
  ALLOWED_MIME_TYPES = 'ALLOWED_MIME_TYPES',

  // Redis
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_DB = 'REDIS_DB',

  // WeChat
  WECHAT_APP_ID = 'WECHAT_APP_ID',
  WECHAT_APP_SECRET = 'WECHAT_APP_SECRET',
  WECHAT_REDIRECT_URI = 'WECHAT_REDIRECT_URI',

  // Content Generation
  DEFAULT_VIDEO_RESOLUTION = 'DEFAULT_VIDEO_RESOLUTION',
  DEFAULT_VIDEO_FPS = 'DEFAULT_VIDEO_FPS',
  DEFAULT_AUDIO_BITRATE = 'DEFAULT_AUDIO_BITRATE',
  DEFAULT_VIDEO_BITRATE = 'DEFAULT_VIDEO_BITRATE',
}
